language: objective-c

osx_image: xcode7.3

install:
  - brew reinstall nvm
  - mkdir -p .nvm
  - export NVM_DIR="$PWD/.nvm"
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install 4.4.0
  - rm -Rf "${TMPDIR}/jest_preprocess_cache"
  - npm config set spin=false
  - npm config set progress=false
  - npm install
  - node --version
  - npm --version

script:
- |
  if [ "$TEST_TYPE" = objc ]
  then
    travis_retry ./scripts/objc-test.sh
  elif [ "$TEST_TYPE" = js ]
  then
    npm run flow && npm test -- --maxWorkers=1
    ./scripts/e2e-test.sh  --packager
  elif [ "$TEST_TYPE" = e2e-objc ]
  then
    ./scripts/e2e-test.sh  --osx
  else
    echo "Unknown test type: $TEST_TYPE"
    exit 1
  fi

env:
  matrix:
    - TEST_TYPE=objc
    - TEST_TYPE=js
  global:
    #- TEST_TYPE=e2e-objc


branches:
  only:
    - master
    - /^.*-stable$/
